services:
  app:
    build: .
    ports:
      - "5000:5000"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
